import { apiFetch } from "../lib/api";
import { getAccessToken } from "../lib/auth";
import type { AgeGroup, ProficiencyLevel, StoryPreference } from "./user";

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "";
const LOG = "[Story API]";

function logRequest(method: string, path: string, body?: unknown) {
    console.log(`${LOG} → ${method} ${path}`, body ?? "");
}

function logResponse(method: string, path: string, data: unknown) {
    console.log(`${LOG} ← ${method} ${path}`, data);
}

// --- 공통 타입 ---

export type StoryToken = {
    id: number;
    text: string;
    highlight: boolean;
    translation: string;
    definition: string;
    audioUrl: string;
    sourceLanguage: string;
    targetLanguage: string;
};

export type StorySlide = {
    slideId: number;
    order: number;
    imageUrl: string;
    textKr: string;
    textNative: string;
    audioUrlKr: string;
    audioUrlNative: string;
    tokens: StoryToken[];
};

export type StoryDetail = {
    storyId: number;
    title: string;
    prompt: string;
    childName: string;
    primaryLanguage: string;
    secondaryLanguage: string;
    isPublic: boolean;
    createdAt: string;
    slides: StorySlide[];
};

type ApiResponse<T> = {
    success: boolean;
    data: T;
    message?: string;
    errorCode?: string;
    timestamp?: string;
};

// --- 1. 동화 생성 작업 요청 POST /api/stories/generate ---

export type GenerateStoryRequest = {
    prompt: string;
    profileId: number;
    childName: string;
    primaryLanguage: string;
    secondaryLanguage: string;
    ageGroup: AgeGroup;
    childAge: number;
    firstLanguageProficiency: ProficiencyLevel;
    secondLanguageProficiency: ProficiencyLevel;
    firstLanguageListening: ProficiencyLevel;
    firstLanguageSpeaking: ProficiencyLevel;
    secondLanguageListening: ProficiencyLevel;
    secondLanguageSpeaking: ProficiencyLevel;
    storyPreference: StoryPreference;
    customStoryPreference?: string;
    autoGenerated: boolean;
    recommendedTaleTitle: string;
};

export type StoryGenerationJob = {
    jobId: string;
    status: string;
    statusUrl?: string;
    resultUrl?: string;
    callbackUrl?: string;
};

export async function generateStory(
    body: GenerateStoryRequest,
): Promise<ApiResponse<StoryGenerationJob>> {
    const path = "/api/stories/generate";
    logRequest("POST", path, body);

    const headers = new Headers({ "Content-Type": "application/json" });
    const token = getAccessToken();
    if (token) {
        headers.set("Authorization", `Bearer ${token}`);
    }

    const response = await fetch(`${API_BASE}${path}`, {
        method: "POST",
        headers,
        body: JSON.stringify(body),
    });

    const parsed = await response.json();

    if (!response.ok) {
        console.error(`${LOG} ✗ POST ${path}`, response.status, parsed);
        throw new Error(`API ${response.status}: ${path}`);
    }

    const job = parseGenerationJob(parsed);
    const result = { success: true, data: job };
    logResponse("POST", path, result);
    return result;
}

function parseGenerationJob(payload: unknown): StoryGenerationJob {
    if (!payload || typeof payload !== "object") {
        throw new Error("동화 생성 작업 응답이 올바르지 않습니다.");
    }

    const record = payload as Record<string, unknown>;
    const data = (record.data ?? record) as Record<string, unknown>;
    const jobId = String(data.jobId ?? "").trim();

    if (!jobId) {
        throw new Error("동화 생성 작업 ID를 받지 못했습니다.");
    }

    return {
        jobId,
        status: String(data.status ?? "queued"),
        statusUrl: data.statusUrl as string | undefined,
        resultUrl: data.resultUrl as string | undefined,
        callbackUrl: data.callbackUrl as string | undefined,
    };
}

// --- 2. 생성된 동화 결과 조회 GET .../generation-jobs/{jobId}/result ---

export type GeneratedSlide = {
    order: number;
    imageUrl: string;
    textKr: string;
    textNative: string;
    audioUrlKr: string;
    audioUrlNative: string;
};

export type StoryGenerateResult = {
    title: string;
    childName: string;
    primaryLanguage: string;
    secondaryLanguage: string;
    slides: GeneratedSlide[];
};

export async function getGenerationJobResult(
    jobId: string,
): Promise<StoryGenerateResult | null> {
    const path = `/api/stories/generation-jobs/${encodeURIComponent(jobId)}/result`;
    logRequest("GET", path);

    const headers = new Headers();
    const token = getAccessToken();
    if (token) {
        headers.set("Authorization", `Bearer ${token}`);
    }

    const response = await fetch(`${API_BASE}${path}`, { headers });

    if (response.status === 409) {
        console.log(`${LOG} ← GET ${path} (409 – 아직 생성 중)`);
        return null;
    }

    const parsed = await response.json();

    if (!response.ok) {
        console.error(`${LOG} ✗ GET ${path}`, response.status, parsed);
        throw new Error(`API ${response.status}: ${path}`);
    }

    const result = parseGenerationResult(parsed);
    logResponse("GET", path, { success: true, data: result });
    return result;
}

function parseGenerationResult(payload: unknown): StoryGenerateResult | null {
    if (!payload || typeof payload !== "object") {
        return null;
    }

    const record = payload as Record<string, unknown>;
    const data = (record.data ?? record) as Record<string, unknown>;
    const slidesRaw = data.slides;

    if (!Array.isArray(slidesRaw) || slidesRaw.length === 0) {
        return null;
    }

    const slides = slidesRaw
        .map((item, index) => normalizeGeneratedSlide(item, index))
        .filter((slide): slide is GeneratedSlide => slide != null);

    if (slides.length === 0) {
        return null;
    }

    return {
        title: String(data.title ?? ""),
        childName: String(data.childName ?? ""),
        primaryLanguage: String(data.primaryLanguage ?? ""),
        secondaryLanguage: String(data.secondaryLanguage ?? ""),
        slides,
    };
}

function normalizeGeneratedSlide(
    item: unknown,
    fallbackOrder: number,
): GeneratedSlide | null {
    if (!item || typeof item !== "object") {
        return null;
    }

    const slide = item as Record<string, unknown>;
    return {
        order: typeof slide.order === "number" ? slide.order : fallbackOrder,
        imageUrl: String(slide.imageUrl ?? ""),
        textKr: String(slide.textKr ?? ""),
        textNative: String(slide.textNative ?? ""),
        audioUrlKr: String(slide.audioUrlKr ?? ""),
        audioUrlNative: String(slide.audioUrlNative ?? ""),
    };
}

// --- 3. 생성 결과 저장 POST /api/stories ---

export type SaveStorySlide = {
    order: number;
    imageUrl: string;
    textKr: string;
    textNative: string;
    audioUrlKr: string;
    audioUrlNative: string;
};

export type SaveStoryRequest = {
    title: string;
    prompt: string;
    profileId: number;
    slides: SaveStorySlide[];
};

export async function saveStory(
    body: SaveStoryRequest,
): Promise<ApiResponse<StoryDetail>> {
    const path = "/api/stories";
    logRequest("POST", path, body);

    const response = (await apiFetch(path, {
        method: "POST",
        body: JSON.stringify(body),
    })) as ApiResponse<StoryDetail>;

    logResponse("POST", path, response);
    return response;
}

// --- 4. 저장된 동화 상세 조회 GET /api/stories/{storyId} ---

export async function getStoryDetail(
    storyId: number,
): Promise<ApiResponse<StoryDetail>> {
    const path = `/api/stories/${storyId}`;
    logRequest("GET", path);

    const response = (await apiFetch(path)) as ApiResponse<StoryDetail>;

    logResponse("GET", path, response);
    return response;
}
