import { apiFetch } from "../lib/api";
import { getAccessToken } from "../lib/auth";
import type {
    AgeGroup,
    FamilyStructure,
    MyPageProfile,
    ProficiencyLevel,
    StoryPreference,
} from "./user";
import KoreaFlag from "../assets/images/tale/flag/korea.png";
import EnglishFlag from "../assets/images/tale/flag/english.png";
import JapanFlag from "../assets/images/tale/flag/japan.png";
import ChinaFlag from "../assets/images/tale/flag/china.png";
import SpainFlag from "../assets/images/tale/flag/spain.png";
import VietnamFlag from "../assets/images/tale/flag/vietnam.png";

export type StoryInitData = {
    profileId: number;
    childName: string;
    firstLanguageDisplay: string;
    secondLanguageDisplay: string;
    ageGroup: AgeGroup;
    childAge: number;
    firstLanguageProficiency: ProficiencyLevel;
    secondLanguageProficiency: ProficiencyLevel;
    firstLanguageListening: ProficiencyLevel;
    firstLanguageSpeaking: ProficiencyLevel;
    secondLanguageListening: ProficiencyLevel;
    secondLanguageSpeaking: ProficiencyLevel;
    storyPreference: StoryPreference;
    customStoryPreference?: string;
    familyStructure: FamilyStructure;
    customFamilyStructure?: string;
    recommendedTaleTitle: string;
    storyId: number | null;
    coverImageUrl: string | null;
};

type StoryInitResponse = {
    success: boolean;
    data: StoryInitData;
};

export const LANGUAGE_OPTIONS = [
    "한국어",
    "영어",
    "일본어",
    "중국어",
    "스페인어",
    "베트남어",
] as const;

export type LanguageDisplay = (typeof LANGUAGE_OPTIONS)[number];

export const LANGUAGE_UI: Record<
    LanguageDisplay,
    { nativeLabel: string; changeLabel: string }
> = {
    한국어: { nativeLabel: "한국어", changeLabel: "변경" },
    영어: { nativeLabel: "English", changeLabel: "Change" },
    일본어: { nativeLabel: "日本語", changeLabel: "変更" },
    중국어: { nativeLabel: "中文", changeLabel: "更改" },
    스페인어: { nativeLabel: "Español", changeLabel: "Cambiar" },
    베트남어: { nativeLabel: "Tiếng Việt", changeLabel: "Thay đổi" },
};

const FLAG_BY_LANGUAGE_DISPLAY: Record<string, string> = {
    한국어: KoreaFlag,
    영어: EnglishFlag,
    일본어: JapanFlag,
    日本語: JapanFlag,
    중국어: ChinaFlag,
    스페인어: SpainFlag,
    베트남어: VietnamFlag,
    KO: KoreaFlag,
    EN: EnglishFlag,
    JA: JapanFlag,
    ZH: ChinaFlag,
    ES: SpainFlag,
    VI: VietnamFlag,
    ko: KoreaFlag,
    en: EnglishFlag,
    ja: JapanFlag,
    zh: ChinaFlag,
    es: SpainFlag,
    vi: VietnamFlag,
};

export function languageDisplayToFlag(display: string): string | undefined {
    return FLAG_BY_LANGUAGE_DISPLAY[display.trim()];
}

export function languageCodeToFlag(code: string): string | undefined {
    const normalized = code.trim();
    return (
        FLAG_BY_LANGUAGE_DISPLAY[normalized] ??
        FLAG_BY_LANGUAGE_DISPLAY[normalized.toLowerCase()] ??
        FLAG_BY_LANGUAGE_DISPLAY[normalized.toUpperCase()]
    );
}

export function getStoryInit(profileId: number) {
    const query = new URLSearchParams({ profileId: String(profileId) });
    return apiFetch(`/api/stories/init?${query}`) as Promise<StoryInitResponse>;
}

const LANGUAGE_DISPLAY_TO_API: Record<LanguageDisplay, string> = {
    한국어: "ko",
    영어: "en",
    일본어: "ja",
    중국어: "zh",
    스페인어: "es",
    베트남어: "vi",
};

export function languageDisplayToApiCode(display: LanguageDisplay): string {
    return LANGUAGE_DISPLAY_TO_API[display];
}

export type GenerateStoryRequest = {
    prompt: string;
    profileId: number;
    childName: string;
    primaryLanguage: string;
    secondaryLanguage: string;
    ageGroup: AgeGroup;
    childAge: number;
    firstLanguageProficiency: ProficiencyLevel;
    secondLanguageProficiency: ProficiencyLevel;
    firstLanguageListening: ProficiencyLevel;
    firstLanguageSpeaking: ProficiencyLevel;
    secondLanguageListening: ProficiencyLevel;
    secondLanguageSpeaking: ProficiencyLevel;
    storyPreference: StoryPreference;
    customStoryPreference?: string;
    autoGenerated: boolean;
    recommendedTaleTitle: string;
};

export type StoryGenerationJob = {
    jobId: string;
    status: string;
    statusUrl?: string;
    resultUrl?: string;
    callbackUrl?: string;
};

export type GeneratedSlide = {
    order: number;
    imageUrl: string;
    textKr: string;
    textNative: string;
    audioUrlKr: string;
    audioUrlNative: string;
};

export type StoryGenerateResult = {
    title: string;
    childName: string;
    primaryLanguage: string;
    secondaryLanguage: string;
    slides: GeneratedSlide[];
};

type ApiResponse<T> = {
    success: boolean;
    data: T;
    message?: string;
    errorCode?: string;
};

export type TaleFlowLocationState = {
    prompt?: string;
    profileId?: number;
    generationError?: string;
};

const JOB_COMPLETE = new Set([
    "completed",
    "complete",
    "success",
    "succeeded",
    "done",
    "finished",
    "ready",
]);
const JOB_FAILED = new Set(["failed", "error", "cancelled", "canceled"]);
const JOB_PENDING = new Set([
    "queued",
    "pending",
    "running",
    "processing",
    "in_progress",
    "in-progress",
    "generating",
]);

export function isGenerationJobComplete(status: string): boolean {
    return JOB_COMPLETE.has(status.trim().toLowerCase());
}

export function isGenerationJobFailed(status: string): boolean {
    const normalized = status.trim().toLowerCase();
    if (!normalized || JOB_PENDING.has(normalized) || JOB_COMPLETE.has(normalized)) {
        return false;
    }
    return JOB_FAILED.has(normalized);
}

function parseGenerationJob(payload: unknown): StoryGenerationJob {
    if (!payload || typeof payload !== "object") {
        throw new Error("동화 생성 작업 응답이 올바르지 않습니다.");
    }

    const record = payload as Record<string, unknown>;
    const data = (record.data ?? record) as Record<string, unknown>;
    const jobId = String(data.jobId ?? data.id ?? "").trim();

    if (!jobId) {
        throw new Error("동화 생성 작업 ID를 받지 못했습니다.");
    }

    return {
        jobId,
        status: String(data.status ?? "queued"),
        statusUrl: data.statusUrl as string | undefined,
        resultUrl: data.resultUrl as string | undefined,
        callbackUrl: data.callbackUrl as string | undefined,
    };
}

function languageSkillsForDisplay(
    profile: MyPageProfile,
    display: LanguageDisplay,
) {
    if (display === profile.firstLanguageDisplay) {
        return {
            proficiency: profile.firstLanguageProficiency,
            listening: profile.firstLanguageListening,
            speaking: profile.firstLanguageSpeaking,
        };
    }
    if (display === profile.secondLanguageDisplay) {
        return {
            proficiency: profile.secondLanguageProficiency,
            listening: profile.secondLanguageListening,
            speaking: profile.secondLanguageSpeaking,
        };
    }
    return {
        proficiency: profile.firstLanguageProficiency,
        listening: profile.firstLanguageListening,
        speaking: profile.firstLanguageSpeaking,
    };
}

export function buildGenerateStoryRequest(
    profile: MyPageProfile,
    init: StoryInitData,
    prompt: string,
    primaryLanguage: LanguageDisplay,
    secondaryLanguage: LanguageDisplay,
): GenerateStoryRequest {
    const primary = languageSkillsForDisplay(profile, primaryLanguage);
    const secondary = languageSkillsForDisplay(profile, secondaryLanguage);

    return {
        prompt: prompt.trim(),
        profileId: profile.profileId,
        childName: profile.childName,
        primaryLanguage: languageDisplayToApiCode(primaryLanguage),
        secondaryLanguage: languageDisplayToApiCode(secondaryLanguage),
        ageGroup: profile.ageGroup,
        childAge: profile.childAge,
        firstLanguageProficiency: primary.proficiency,
        secondLanguageProficiency: secondary.proficiency,
        firstLanguageListening: primary.listening,
        firstLanguageSpeaking: primary.speaking,
        secondLanguageListening: secondary.listening,
        secondLanguageSpeaking: secondary.speaking,
        storyPreference: profile.storyPreference,
        customStoryPreference: profile.customStoryPreference,
        autoGenerated: false,
        recommendedTaleTitle: init.recommendedTaleTitle,
    };
}

export async function generateStory(body: GenerateStoryRequest) {
    const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "";
    const headers = new Headers({ "Content-Type": "application/json" });
    const token = getAccessToken();
    if (token) {
        headers.set("Authorization", `Bearer ${token}`);
    }

    const response = await fetch(`${API_BASE}/api/stories/generate`, {
        method: "POST",
        headers,
        body: JSON.stringify(body),
    });

    if (!response.ok) {
        throw new Error(`API ${response.status}: /api/stories/generate`);
    }

    const parsed = await response.json();
    const job = parseGenerationJob(parsed);

    return {
        success: true,
        data: job,
    };
}

export function getGenerationJobStatus(jobId: string) {
    return apiFetch(
        `/api/stories/generation-jobs/${encodeURIComponent(jobId)}`,
    ) as Promise<ApiResponse<StoryGenerationJob>>;
}

export async function getGenerationJobResult(jobId: string) {
    const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "";
    const headers = new Headers();
    const token = getAccessToken();
    if (token) {
        headers.set("Authorization", `Bearer ${token}`);
    }

    const response = await fetch(
        `${API_BASE}/api/stories/generation-jobs/${encodeURIComponent(jobId)}/result`,
        { headers },
    );

    if (response.status === 409) {
        return null;
    }

    if (!response.ok) {
        throw new Error(
            `API ${response.status}: /api/stories/generation-jobs/${jobId}/result`,
        );
    }

    return response.json() as Promise<ApiResponse<StoryGenerateResult>>;
}

export async function pollGenerationJob(
    jobId: string,
    options?: { intervalMs?: number; onStatus?: (status: string) => void },
): Promise<StoryGenerateResult> {
    const intervalMs = options?.intervalMs ?? 2500;

    for (;;) {
        const { data: job } = await getGenerationJobStatus(jobId);
        options?.onStatus?.(job.status);

        if (isGenerationJobFailed(job.status)) {
            throw new Error("동화 생성에 실패했습니다.");
        }

        if (isGenerationJobComplete(job.status)) {
            const resultResponse = await getGenerationJobResult(jobId);
            if (resultResponse?.data?.slides?.length) {
                return resultResponse.data;
            }
        }

        await new Promise((resolve) => window.setTimeout(resolve, intervalMs));
    }
}
